// Command surface-dump prints the CLI's public command surface as
// deterministic JSON: every command path, its flags, and its argument spec.
//
// It exists to make surface changes reviewable. ~95% of the command tree is
// regenerated from openapi.yaml, so a renamed field or endpoint propagates
// straight into commands and flags with nothing forcing a human to look at
// it. CI regenerates this manifest and diffs it against the committed
// surface.json; any mismatch fails until the PR commits the new manifest
// (`go run ./cmd/surface-dump -write`), which puts the exact surface change
// in the PR diff where a reviewer can see it.
//
// This binary is never shipped. It registers the command tree exactly like
// cmd/orq and then only walks it.
package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"os"
	"sort"
	"strings"

	bartolocli "github.com/orq-ai/bartolo/cli"
	pflag "github.com/spf13/pflag"

	custom "orq/cli/custom"
	generated "orq/cli/generated"

	"github.com/spf13/cobra"
)

// manifestPath is relative to the repo root, where CI runs this tool.
const manifestPath = "surface.json"

type flagSpec struct {
	Name       string `json:"name"`
	Shorthand  string `json:"shorthand,omitempty"`
	Type       string `json:"type"`
	Persistent bool   `json:"persistent,omitempty"`
}

type commandSpec struct {
	Path    string     `json:"path"`
	Use     string     `json:"use"`
	Aliases []string   `json:"aliases,omitempty"`
	Hidden  bool       `json:"hidden,omitempty"`
	Flags   []flagSpec `json:"flags,omitempty"`
}

type surface struct {
	// Note is for human readers of the committed file, not consumed by code.
	Note     string        `json:"_note"`
	Commands []commandSpec `json:"commands"`
}

func collectFlags(fs *pflag.FlagSet, persistent bool, out *[]flagSpec, seen map[string]bool) {
	fs.VisitAll(func(f *pflag.Flag) {
		if seen[f.Name] {
			return
		}
		seen[f.Name] = true
		*out = append(*out, flagSpec{
			Name:       f.Name,
			Shorthand:  f.Shorthand,
			Type:       f.Value.Type(),
			Persistent: persistent,
		})
	})
}

func walk(cmd *cobra.Command, prefix string, out *[]commandSpec) {
	name := cmd.Name()
	use := cmd.Use
	if prefix == "" {
		// The root command's name AND Use come from argv (the surface-dump
		// binary), which would make the manifest depend on how this tool was
		// invoked. Pin both to "orq" — pinning only name left Use recording the
		// binary name, and any build that names the binary differently
		// (`go build -o /tmp/sd`) then tripped -check on a non-surface diff.
		name, use = "orq", "orq"
	}
	path := strings.TrimSpace(prefix + " " + name)
	var flags []flagSpec
	seen := map[string]bool{}
	// LocalFlags includes persistent flags declared ON this command;
	// listing local first keeps a flag that exists in both marked local.
	collectFlags(cmd.LocalFlags(), false, &flags, seen)
	collectFlags(cmd.PersistentFlags(), true, &flags, seen)
	sort.Slice(flags, func(i, j int) bool { return flags[i].Name < flags[j].Name })
	*out = append(*out, commandSpec{
		Path:    path,
		Use:     use,
		Aliases: append([]string(nil), cmd.Aliases...),
		Hidden:  cmd.Hidden,
		Flags:   flags,
	})
	children := append([]*cobra.Command(nil), cmd.Commands()...)
	sort.Slice(children, func(i, j int) bool { return children[i].Name() < children[j].Name() })
	for _, c := range children {
		walk(c, path, out)
	}
}

func dump() ([]byte, error) {
	bartolocli.Init(&bartolocli.Config{
		AppName:             "orq",
		EnvPrefix:           "ORQ",
		APIKeyEnvVar:        "ORQ_API_KEY",
		DefaultOutputFormat: "toon",
		Version:             "surface", // fixed: the manifest must not churn per release
	})
	generated.Register(bartolocli.Root)
	custom.Register(bartolocli.Root)

	// Reported here because this is the tool a regeneration forces you to run:
	// a new openapi.yaml tag becomes a top-level command with no topic, and
	// help then files it under Utilities, which is a wrong section rather than
	// a missing one. Not fatal — the manifest still has to be written — but it
	// names the edit while the person making the change is still looking at it.
	if ungrouped := custom.UngroupedCommands(bartolocli.Root); len(ungrouped) > 0 {
		fmt.Fprintf(os.Stderr,
			"surface-dump: %d new command(s) have no help group: %s\n"+
				"Add them to commandGroup in cli/custom/groups.go, or to\n"+
				"deliberateUtilities if Utilities is genuinely where they belong.\n",
			len(ungrouped), strings.Join(ungrouped, ", "))
	}

	var commands []commandSpec
	walk(bartolocli.Root, "", &commands)
	sort.Slice(commands, func(i, j int) bool { return commands[i].Path < commands[j].Path })
	s := surface{
		Note: "Generated by `go run ./cmd/surface-dump -write`. CI fails when this file " +
			"does not match the registered command tree, so surface changes (especially " +
			"from OpenAPI regeneration) are always visible in a PR diff. Removing or " +
			"renaming a command or flag is a breaking change: announce it in CHANGELOG.md " +
			"one release before it disappears.",
		Commands: commands,
	}
	data, err := json.MarshalIndent(s, "", "  ")
	if err != nil {
		return nil, err
	}
	return append(data, '\n'), nil
}

func main() {
	write := flag.Bool("write", false, "write the manifest to "+manifestPath+" instead of stdout")
	check := flag.Bool("check", false, "exit 1 if "+manifestPath+" does not match the current command tree")
	flag.Parse()

	data, err := dump()
	if err != nil {
		fmt.Fprintln(os.Stderr, "surface-dump:", err)
		os.Exit(1)
	}
	switch {
	case *check:
		committed, err := os.ReadFile(manifestPath)
		if err != nil {
			fmt.Fprintf(os.Stderr, "surface-dump: cannot read %s: %v\n", manifestPath, err)
			os.Exit(1)
		}
		if string(committed) != string(data) {
			fmt.Fprintf(os.Stderr,
				"surface-dump: %s does not match the registered command tree.\n"+
					"The CLI surface changed. Run `go run ./cmd/surface-dump -write`, review the\n"+
					"diff (removals and renames are breaking; see CHANGELOG.md), and commit it.\n",
				manifestPath)
			os.Exit(1)
		}
		fmt.Println("surface.json matches the registered command tree")
	case *write:
		if err := os.WriteFile(manifestPath, data, 0o644); err != nil {
			fmt.Fprintln(os.Stderr, "surface-dump:", err)
			os.Exit(1)
		}
		fmt.Println("wrote", manifestPath)
	default:
		os.Stdout.Write(data)
	}
}
